[aws]
format = 'on [$symbol($profile )(\($region\) )]($style)'
style = "bold blue"
symbol =" " 

[lua]
symbol=' '
[python]
# symbol  = '[ ](fg:#ffd43b)'
symbol  = '[ ](fg:#4b8bbe)'
# style  = 'fg:#4b8bbe'
style  = 'fg:#ffd43b'
format = '[${symbol}${pyenv_prefix}(${version} )]($style)[(\($virtualenv\) )](fg:#646464)'

[ directory ]
style  = 'fg:#FF10F0'

[custom.zsh]
when = '[[ ! -n "${VIRTUAL_ENV}" ]]'
style = "bold red"
format = '[ NO PYTHON VENV SET ]($style)'
