- name: Install System Packages 1 (terminal)
  become_user: root
  apt:
    name: 
      - build-essential
      - ccache
      - cmake
      - curl
      - dconf-editor
      - gettext
      - golang
      - htop
      - libpthread-stubs0-dev
      - libtool
      - libtool-bin
      - lsof
      - lua5.1
      - ninja-build
      - pkg-config
      - python3-pip
      - stow
      - unzip
  tags:
    - install
    - terminal
    - neovim
    - nvim
    - core

- name: pipx
  pip:
    name: pipx
  tags:
    - install
    - terminal
    - core
    - pipx
