- name: Install System Packages 1 (terminal)
  become_user: root
  apt:
    name: 
      - build-essential
      - ccache
      - cmake
      - curl
      - dconf-editor
      - direnv
      - gettext
      - golang
      - htop
      - libevent-dev
      - libpthread-stubs0-dev
      - libtool
      - libtool-bin
      - lsof
      - lua5.1
      - neofetch
      - ninja-build
      - pkg-config
      - python3-dev
      - python3-pip
      - python3-venv
      - rename
      - silversearcher-ag
      - stow
      - tree
      - unzip
      - webp
  tags:
    - install
    - terminal
    - neovim
    - nvim
    - core

- name: install nix
  shell: |
    sudo install -d -m755 -o $(id -u) -g $(id -g) /nix
    curl -L https://nixos.org/nix/install | sh
  tags:
    - install
    - terminal
    - core
    - direnv

- name: pipx
  pip:
    name: pipx
  tags:
    - install
    - terminal
    - core
    - pipx

- name: Add another bin dir to system-wide $PATH.
  become_user: root
  copy:
    dest: /etc/profile.d/custom-path.sh
    content: 'export "PATH=$PATH:~/.local/bin"'

- name: pipx ensurepath
  shell: pipx ensurepath
  tags:
    - install
    - terminal
    - core
    - pipx

- name: set python3 as default python
  shell: update-alternatives --install {{ lookup('env', 'HOME') }}/.local/bin/python python `which python3` 20
  tags:
    - install
    - terminal
    - core
    - python

- name: set python3 as default python
  shell: update-alternatives --install {{ lookup('env', 'HOME') }}.local/bin/python3 python3 `which python3` 20
  tags:
    - install
    - terminal
    - core
    - python
