- name: Install System Packages 1 (terminal)
  become_user: root
  apt:
    name: 
      - build-essential
      - ccache
      - cmake
      - curl
      - dconf-editor
      - direnv
      - gettext
      - golang
      - htop
      - libevent-dev
      - libpthread-stubs0-dev
      - libtool
      - libtool-bin
      - lsof
      - lua5.1
      - ninja-build
      - pkg-config
      - python3-pip
      - python3.8-dev
      - python3.8-venv
      - stow
      - unzip
  tags:
    - install
    - terminal
    - neovim
    - nvim
    - core

- name: install nix
  shell: curl -L https://nixos.org/nix/install | sh
  tags:
    - install
    - terminal
    - core
    - direnv

- name: pipx
  pip:
    name: pipx
  tags:
    - install
    - terminal
    - core
    - pipx

- name: Add another bin dir to system-wide $PATH.
  become_user: root
  copy:
    dest: /etc/profile.d/custom-path.sh
    content: 'export "PATH=$PATH:~/.local/bin"'

- name: pipx ensurepath
  shell: pipx ensurepath
  tags:
    - install
    - terminal
    - core
    - pipx

