- name: kdenlive ppa (ppa:kdenlive/kdenlive-stable)
  apt_repository:
   repo: ppa:kdenlive/kdenlive-stable
   state: present
   update_cache: True
  tags:
    - install
    - productivity
- name: Install packages
  become_user: root
  apt:
    name:
      - wireshark
      - fzf
      - kdenlive
      - gimp
      - vlc
      - xclip
      - screenkey
      - tldr
      - compton
      - rofi
      - lxappearance
      - flameshot
      - awesome
      - xbindkeys
      - pavucontrol
  tags:
    - install
    - productivity
    - productivity-apt
- name: install sphinx-build
  become_user: root
  apt: name=python3-sphinx
  tags: 
    - productivity
    - polybar
- name: install polybar
  shell: |
    sudo apt-get install cmake cmake-data libcairo2-dev libxcb1-dev libxcb-ewmh-dev libxcb-composite0-dev libjsoncpp-dev libxcb-randr0-dev xcb-proto python3-sphinx
    sudo ln -s /usr/include/jsoncpp/json/ /usr/include/json
    cd ~/tmp
    git clone https://github.com/jaagr/polybar.git
    cd polybar
    ./build.sh
    sudo apt purge python3-sphinx
  tags:
    - productivity
    - polybar

- name: uninstall kdenlive
  shell: rm `which kdenlive`
  tags:
    - productivity
    - kdenlive
- name: install kdenlive
  get_url:
    url: https://download.kde.org/stable/kdenlive/21.08/linux/kdenlive-21.08.1-x86_64.appimage 
    dest: "{{ lookup('env', 'HOME') }}/.local/bin/kdenlive"
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('env', 'USER') }}"
    mode: '0755'
  tags:
    - desktop
    - kdenlive
- name: clone v4l2loopback
  ansible.builtin.git:
    repo: 'https://github.com/umlaeute/v4l2loopback.git'
    dest: "{{ lookup('env', 'HOME') }}/git/v4l2loopback"
    update: no
  tags:
    - desktop
    - obs
    - v4l2loopback
- name: Build 4v4l2loopback
  shell: "cd {{ lookup('env', 'HOME') }}/git/v4l2loopback && make"
  tags:
    - desktop
    - obs
    - v4l2loopback
- name: install v4l2loopback
  shell: "cd {{ lookup('env', 'HOME') }}/git/v4l2loopback sudo make install"
  tags:
    - desktop
    - obs
    - v4l2loopback

- name: rofimoji deps
  apt: name={{item}}
  become_user: root
  with_items:
    - fonts-emojione
    - python3
    - rofi
    - xdotool
    - xsel
  tags:
    - install
    - dotfiles
    - rofimoji

- name: Setup rofimoji
  shell: pipx install rofimoji --force
  tags:
    - install
    - dotfiles
    - rofimoji

