- name: Install packages
  become_user: root
  apt:
    name:
      - awesome
      - arandr
      - compton
      - flameshot
      - fzf
      - gimp
      - lxappearance
      - pavucontrol
      - rofi
      - screenkey
      - tldr
      - vlc
      - wireshark
      - xbindkeys
      - xclip
  tags:
    - install
    - desktop
    - desktop-apt
- name: install sphinx-build
  become_user: root
  apt: name=python3-sphinx
  tags: 
    - desktop
    - polybar
- name: install polybar
  shell: |
    sudo apt-get install cmake cmake-data libcairo2-dev libxcb1-dev libxcb-ewmh-dev libxcb-composite0-dev libjsoncpp-dev libxcb-randr0-dev xcb-proto python3-sphinx
    sudo ln -s /usr/include/jsoncpp/json/ /usr/include/json
    cd ~/tmp
    git clone https://github.com/jaagr/polybar.git
    cd polybar
    ./build.sh
    sudo apt purge python3-sphinx
  tags:
    - desktop
    - polybar

- name: uninstall kdenlive
  shell: rm `which kdenlive`
  tags:
    - desktop
    - kdenlive
- name: install kdenlive
  get_url:
    url: https://download.kde.org/stable/kdenlive/21.08/linux/kdenlive-21.08.1-x86_64.appimage 
    dest: "{{ lookup('env', 'HOME') }}/.local/bin/kdenlive"
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('env', 'USER') }}"
    mode: '0755'
  tags:
    - desktop
    - kdenlive
- name: clone v4l2loopback
  ansible.builtin.git:
    repo: 'https://github.com/umlaeute/v4l2loopback.git'
    dest: "{{ lookup('env', 'HOME') }}/git/v4l2loopback"
    update: no
  tags:
    - desktop
    - obs
    - v4l2loopback
- name: Build 4v4l2loopback
  shell: "cd {{ lookup('env', 'HOME') }}/git/v4l2loopback && make"
  tags:
    - desktop
    - obs
    - v4l2loopback
- name: install v4l2loopback
  shell: "cd {{ lookup('env', 'HOME') }}/git/v4l2loopback sudo make install"
  tags:
    - desktop
    - obs
    - v4l2loopback

- name: rofimoji deps
  apt: name={{item}}
  become_user: root
  with_items:
    - fonts-emojione
    - python3
    - rofi
    - xdotool
    - xsel
  tags:
    - install
    - dotfiles
    - rofimoji

- name: Setup rofimoji
  shell: pipx install rofimoji --force
  tags:
    - install
    - dotfiles
    - rofimoji
- name: Install signal
  shell: |
    # NOTE: These instructions only work for 64 bit Debian-based
    # Linux distributions such as Ubuntu, Mint etc.

    # 1. Install our official public software signing key
    wget -O- https://updates.signal.org/desktop/apt/keys.asc | gpg --dearmor > signal-desktop-keyring.gpg
    cat signal-desktop-keyring.gpg | sudo tee -a /usr/share/keyrings/signal-desktop-keyring.gpg > /dev/null

    # 2. Add our repository to your list of repositories
    echo 'deb [arch=amd64 signed-by=/usr/share/keyrings/signal-desktop-keyring.gpg] https://updates.signal.org/desktop/apt xenial main' |\
      sudo tee -a /etc/apt/sources.list.d/signal-xenial.list

    # 3. Update your package database and install signal
    sudo apt update && sudo apt install signal-desktop

  tags:
    - signal
