- name: Install nodejs and npm
  become_user: root
  apt:
    name: ["nodejs", "npm"]
  tags:
    - install
    - terminal
    - node
    - nvim
    - neovim
- name: Install N
  npm:
    name: n
    global: yes
  tags:
    - install
    - terminal
    - node
    - nvim
    - neovim
- name: Install correct version of Node
  shell: n 14
  tags:
    - install
    - terminal
    - node
    - nvim
    - neovim
- name: Set Global npm directory
  shell: |
    mkdir ~/.npm-global
    npm config set prefix '~/.npm-global'
  tags:
    - install
    - terminal
    - node
    - nvim
    - neovim
    - npm
