- name: Clone Neovim
  ansible.builtin.git:
    repo: 'https://github.com/neovim/neovim.git'
    dest: "{{ lookup('env', 'HOME') }}/neovim"
  tags:
    - install
    - neovim
    - nvim
- name: Build neovim
  shell: "cd {{ lookup('env', 'HOME') }}/neovim && make"
  tags:
    - install
    - neovim
    - nvim
- name: Install neovim
  shell: "cd {{ lookup('env', 'HOME') }}/neovim && sudo make install"
  tags:
    - install
    - neovim
    - nvim
- name: Neovim Plugin Development 1
  become_user: root
  apt: name=luarocks
  tags:
    - install
    - neovim
    - nvim
- name: Neovim Plugin Development 2 luacheck
  shell: luarocks install luacheck
  become_user: root
  tags:
    - install
    - neovim
    - nvim
- name: Install Vim-Plug
  shell: curl -fLo {{ lookup('env', 'HOME') }}/.local/share/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  tags:
    - install
    - dotfiles
    - plugged
    - neovim
    - nvim
- name: Install vim Plugins
  ignore_errors: yes
  shell: nvim +PlugInstall +qall
  tags:
    - install
    - dotfiles
    - neovim
    - nvim
