- name: Clone Neovim
  ansible.builtin.git:
    repo: 'https://github.com/neovim/neovim.git'
    dest: "{{ lookup('env', 'HOME') }}/third-party/neovim"
    update: yes
  tags:
    - install
    - terminal
    - neovim
    - nvim


- name: Build neovim
  become_user: root
  shell: "cd {{ lookup('env', 'HOME') }}/third-party/neovim && sudo make CMAKE_INSTALL_PREFIX={{ lookup('env', 'home') }}/third-party/neovim"
  tags:
    - install
    - terminal
    - neovim
    - nvim

- name: Install neovim
  shell: "cd {{ lookup('env', 'HOME') }}/third-party/neovim && sudo make install"
  tags:
    - install
    - terminal
    - neovim
    - nvim

- name: Install pynvim venv3
  shell: |
    cd {{ lookup('env', 'HOME') }}/.config/nvim/
    python3 -m venv .venv3  --prompt nvim3
  tags:
    - install
    - terminal
    - neovim
    - nvim
    - pynvim

- name: Install pynvim into venv3
  pip:
    name: pynvim
    virtualenv: "{{ lookup('env', 'HOME') }}/.config/nvim/.venv3"
  tags:
    - install
    - terminal
    - neovim
    - nvim
    - pynvim

- name: Install neovim venv2
  shell: |
    cd {{ lookup('env', 'HOME') }}/.config/nvim/
    python2 -m virtualenv .venv2  --prompt nvim2
  tags:
    - install
    - terminal
    - neovim
    - nvim
    - pynvim

- name: Install pynvim into venv2
  pip:
    name: pynvim
    virtualenv: "{{ lookup('env', 'HOME') }}/.config/nvim/.venv2"
  tags:
    - install
    - terminal
    - neovim
    - nvim
    - pynvim



- name: Neovim Plugin Development 1
  become_user: root
  apt: name=luarocks
  tags:
    - install
    - terminal
    # - neovim
    # - nvim
- name: Neovim Plugin Development 2 luacheck
  shell: luarocks install luacheck
  become_user: root
  tags:
    - install
    - terminal
    - neovim
    - nvim
- name: Install Vim-Plug
  shell: curl -fLo {{ lookup('env', 'HOME') }}/.local/share/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  tags:
    - install
    - terminal
    - dotfiles
    - plugged
    - neovim
    - nvim
- name: Install vim Plugins
  ignore_errors: yes
  shell: nvim -u ~/.config/nvim/plugins.vim +PlugInstall +qall
  tags:
    - install
    - terminal
    - dotfiles
    - neovim
    - nvim
- name: Setup python-lsp-server
  shell: pipx install 'python-lsp-server[all]' --force
  tags:
    - lsp
    - install
    - terminal
    - dotfiles
    - neovim
    - nvim
    - python-lsp
- name: Setup pylsp-mypy
  shell: pipx inject python-lsp-server pylsp-mypy --force
  tags:
    - lsp
    - install
    - terminal
    - dotfiles
    - neovim
    - nvim
    - python-lsp
- name: Setup jedi-language-server
  shell: pipx install jedi-language-server --force
  tags:
    - lsp
    - install
    - terminal
    - dotfiles
    - neovim
    - nvim
    - python-lsp
- name: Setup yaml language server
  shell: npm i -g yaml-language-server@latest
  tags:
    - lsp
    - install
    - terminal
    - dotfiles
    - neovim
    - nvim
    - yaml-lsp

- name: Setup html language server
  shell: npm i -g vscode-langservers-extracted
  tags:
    - lsp
    - install
    - terminal
    - dotfiles
    - neovim
    - nvim
    - html-lsp

- name: Setup bash language server
  shell: npm i -g bash-language-server@latest
  tags:
    - lsp
    - install
    - terminal
    - dotfiles
    - neovim
    - nvim
    - bash-lsp

- name: Clone sumneko lua-language-server
  ansible.builtin.git:
    repo: https://github.com/sumneko/lua-language-server
    dest: "{{ lookup('env', 'HOME') }}/third-party/lua-language-server"
    update: yes
  tags:
    - lua-lsp

- name: setup sumneko lua-language-server
  shell: |
    cd "{{ lookup('env', 'HOME') }}/third-party/lua-language-server"
    git submodule update --init --recursive
    cd 3rd/luamake
    compile/install.sh
    cd ../..
    ./3rd/luamake/luamake rebuild
  tags:
    - lsp
    - install
    - terminal
    - dotfiles
    - neovim
    - nvim
    - lua-lsp

- name: include sumneko lua-language-server path in .profile
  blockinfile:
    dest: "{{ lookup('env', 'HOME') }}/.profile"

    marker: '# {mark} sumneko lua-language-server path added by devtainer'
    block: |
      # set PATH so it includes user's lua-language-server bin if it exists
      if [ -d "$HOME/third-party/lua-language-server/bin/Linux/" ] ; then
        PATH="$PATH:$HOME/third-party/lua-language-server/bin/Linux/"
      fi
    state: present
  become: yes
  tags:
    - lsp
    - install
    - terminal
    - dotfiles
    - neovim
    - nvim
    - neovim
