- hosts: localhost
  gather_facts: true
  become: true
  become_user: "{{ lookup('env', 'USER') }}"

  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      become_user: root
      changed_when: False
  tasks:
    - include: tasks/core-setup.yml
    - include: tasks/repos.yml
    - include: tasks/node-setup.yml
    - include: tasks/nvim-setup.yml
    - include: tasks/zsh-setup.yml
    - include: tasks/desktop.yml
    - include: tasks/brave.yml
    - include: tasks/obs.yml
